-name: shabbu
  email: shabanashaik75@gmail.com
  addresses: #list
    -type: perminent address
      doNO: 15-33
      street: zenda chettu center
      City: Nambur
    -type: temporary address
      doNO: 111
      street: gachibowli
      City: hyd

