- name: installing and run nginx
  hosts: web
  become: yes # -b giving root access
  tasks:
    - name: install nginx
      ansible.builtin.package:
       name: nginx
       state: present    #present means install,absent means remove
    - name: start the nginx
      ansible.builtin.service:
       name: nginx
       state: started
       enabled: yes
      