- name: installing and nginx
  hosts: web
  tasks:
    - name: install nginx
      ansible.builtin.debug:
      name: nginx
      state: present    #present means install,absent means remove
    - name: start nginx
      ansible.builtin.debug:
      name: nginx
      state: started
      enabled: yes
      