- name: installing and starting nginx
  hosts: web
  tasks:
    - name: install nginx
      ansible.builtin.debug:
      name: nginx
      state: absent    #present means install,absent means remove
    # - name: start nginx
    #   ansible.builtin.debug:
    #   name: nginx
    #   state: started
    #   enabled: yes
