- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "devops with aws"
    DURATION: 129hrs
    TRAINER: shiva kumar
  tasks:
    - name: print the variable
      ansible.builtin.debug:
      msg: "course is {{COURSE}}, duration is {{DURATION}}, trainer name is {{TRAINER}}"  