- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variable
    ansible.builtin.debug:
      msg: "hello {{ person | default('ramesh') }}"    #person is a variable

  - name: convert string to list
    vars:
      fruits: " apple, banana, mango, orange "  #string
    ansible.builtin.debug:
      msg: "fruits are{{ fruits | split(',') }}"     

  - name: convert map to list
    vars:
      course:
        name: ansible
        duration: 120hrs
        trainer: shiva    #map
    ansible.builtin.debug:
      msg: "course info {{ course | dict2items }}"     

  - name: convert list to map
    vars:
      course:
        - {'key': 'name', 'value': 'ansible'}    
        - {'key': 'duration', 'value': 'one week'}  
        - {'key': 'trainer', 'value': 'shiva'}  
    ansible.builtin.debug:
      msg: "courses are {{ course | items2dict}}"    

  - name: convert upper to lower
    vars:
      name: "SHABBU shaik"
    ansible.builtin.debug:
      msg: "this is lower case: {{ name | lower }}"

  - name: convert lower to upper
    vars:
      name: "SHABBU shaik"
    ansible.builtin.debug:
      msg: "this is upper case- {{ name | upper }}"    

  - name: print min and mx
    vars:
      number: [1, 50, 999, 67, 43 ]
    ansible.builtin.debug:
      msg: "min is {{ number | min}} and max is {{ number | max }}"      

  - name: check IP address is valid or not
    vars:
      IP: "192.143.150.0"
    ansible.builtin.debug:
      msg:  "{{ IP | ansible.utils.ipaddr }}" 
