- name: filters
  hosts: local
  connection: local
  become: yes
  tasks:
  - name:handle undefined variable
    ansible.builtin.debug:
      msg: "hello {{ person | default('ramesh') }}"    #person is a variable